ble_src_file: [fix] remove unused but treated like error
Error message:
../main/src/ble/hid_device_le_prf.c
../main/src/ble/hid_device_le_prf.c:285:22: error: 'char_prop_read_write_notify' defined but not used [-Werror=unused-const-variable=]
  285 | static const uint8_t char_prop_read_write_notify = ESP_GATT_CHAR_PROP_BIT_READ|ESP_GATT_CHAR_PROP_BIT_WRITE|ESP_GATT_CHAR_PROP_BIT_NOTIFY;
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../main/src/ble/hid_device_le_prf.c:280:22: error: 'char_prop_notify' defined but not used [-Werror=unused-const-variable=]
  280 | static const uint8_t char_prop_notify = ESP_GATT_CHAR_PROP_BIT_NOTIFY;
      |                      ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/taltal/git/esp/examples/mode_change/build/log/idf_py_stderr_output_120457 and /home/taltal/git/esp/examples/mode_change/build/log/idf_py_stdout_output_120457